
services:
  voyager:
    build:
      context: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MINECRAFT_LAN_PORT: 43481
      MINECRAFT_OPENAI_KEY: "***REMOVED***"