version: "3"

services:
  voyager:
    build:
      context: voyager_service
    depends_on: 
      minecraft:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file: openai.env
    environment:
      MINECRAFT_LAN_PORT: 25565
      MINECRAFT_LAN_HOST: minecraft
      # MINECRAFT_LAN_HOST: host.docker.internal
    command:
      python3 -u runner.py
    volumes:
      - ./voyager_service/Voyager/voyager/prompts:/Voyager-compose/Voyager/voyager/prompts
  minecraft:
    build:
      context: minecraft_server_service
    healthcheck:
      test: python3 -c 'import mcstatus; mcstatus.JavaServer("localhost", 25565).status()'
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 2m
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.19
      DIFFICULTY: peaceful
      MODE: survival
      TYPE: FABRIC
      FABRIC_LAUNCHER_VERSION: 0.11.2
      FABRIC_LOADER_VERSION: 0.14.8
      COPY_CONFIG_DEST: /data/config
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
      ONLINE_MODE: "FALSE"
      RCON_CMDS_STARTUP:  |-
        /difficulty peaceful
        /defaultgamemode survival
      RCON_CMDS_ON_CONNECT: |
        /op @a
        /gamemode survival @a
      MODS: |
        /mods/better-respawn-fabric-1.19-2.0.0.jar
        /mods/completeconfig-2.0.0.jar
        /mods/fabric-api-0.58.0+1.19.jar
        /mods/modmenu-4.0.4.jar
        /mods/Multiplayer-Server-Pause-1.19-Fabric-1.1.0.jar
    volumes:
      - ./minecraft_server_service/data:/data
      - ./minecraft_server_service/mods:/mods
      - ./minecraft_server_service/config:/config
